//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkillsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationEvent
    {
        public int RegistrationEventId { get; set; }
        public int RegistrationId { get; set; }
        public string EventId { get; set; }
        public Nullable<short> BibNumber { get; set; }
        public Nullable<int> RaceTime { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Registration Registration { get; set; }

        /// <summary>
        /// Определяет возратсную категорию бегуна
        /// </summary>
        /// <param name="DateOfBirth">дата рождения</param>
        /// <param name="CalcTime">дата, относительно которой надо вычитать категорию</param>
        /// <returns></returns>
        public string GetCategory
        {
            get
            {
                DateTime DateBirth = (DateTime)Registration.Runner.DateOfBirth;
                DateTime CalcDate = (DateTime)Event.StartDateTime;
                TimeSpan delta = CalcDate - DateBirth;
                if (delta < (CalcDate - new DateTime(CalcDate.Year - 18, CalcDate.Month, CalcDate.Day))) return "до 18";
                if (delta < (CalcDate - new DateTime(CalcDate.Year - 30, CalcDate.Month, CalcDate.Day))) return "18-29";
                if (delta < (CalcDate - new DateTime(CalcDate.Year - 40, CalcDate.Month, CalcDate.Day))) return "30-39";
                if (delta < (CalcDate - new DateTime(CalcDate.Year - 56, CalcDate.Month, CalcDate.Day))) return "40-55";
                if (delta < (CalcDate - new DateTime(CalcDate.Year - 70, CalcDate.Month, CalcDate.Day))) return "56-70";
                else return "более 70";
            }
        }
    }
}
