//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkillsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public int SponsorshipId { get; set; }
        public string SponsorName { get; set; }
        public int RegistrationId { get; set; }
        public decimal Amount { get; set; }

        public string GetFullName
        {
            get
            {
                return $"{Registration.Runner.User.FirstName} {Registration.Runner.User.LastName} ({Registration.Runner.RunnerId}) из {Registration.Runner.Country.CountryName}";
            }
        }
    
        public virtual Registration Registration { get; set; }
    }
}
