//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkillsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInventar
    {
        public int Id { get; set; }
        public string InvName { get; set; }
        public int Stock { get; set; }
    }
}
